### ISSUE TITLE
Get_Server Mysql connection query error

### ISSUE THREAD

**Issue by a7mdragab** [jonataslaw/get_server#67]
I have used  to connect to mysql

when I try this code,
```
var settings = ConnectionSettings(
          host: 'localhost',
          port: 3306,
          user: 'root',
          password: '12345678',
          db: 'taxilv');
      var mySqlConnection = await MySqlConnection.connect(settings);
      var res = await mySqlConnection!.query('select name, email from users where id = ?', [1]);
```
 I get this error
```
Unhandled exception:
RangeError (byteOffset): Invalid value: Not in inclusive range 0..5: 7
#0      _ByteDataView.getUint16 (dart:typed_data-patch/typed_data_patch.dart:4799)
#1      Buffer.readUint16 (package:mysql1/src/buffer.dart:240)
#2      new PrepareOkPacket (package:mysql1/src/prepared_statements/prepare_ok_packet.dart:20)
#3      Handler.checkResponse (package:mysql1/src/handlers/handler.dart:68)
#4      PrepareHandler.processResponse (package:mysql1/src/prepared_statements/prepare_handler.dart:45)
#5      ReqRespConnection._handleData (package:mysql1/src/single_connection.dart:349)
#6      ReqRespConnection._handleHeader (package:mysql1/src/single_connection.dart:318)
<asynchronous suspension>
#7      ReqRespConnection._readPacket (package:mysql1/src/single_connection.dart:303)
<asynchronous suspension>
```

**Comment by tang85** [comment]
change

**Comment by tang85** [comment]
change  var res = await mySqlConnection!.query('select name, email from users where id = ?', [1]);

**Comment by andersondantas81** [comment]
Adiciona um delay e 1 segundo que dar certo.

**Comment by daniloc7** [comment]
Como q faz isso, Anderson? Eu tentei de um jeito com future.delayed mas mesmo assim da erro.
